---
# tasks file for rhcos_install

- name: restart in rescue mode 
  hcloud_server:
    name: '{{ item.name }}'
    api_token: "{{ token }}"
    ssh_keys: "{{ item.ssh_key }}"
    rescue_mode: linux64
    state: restarted
  loop: "{{ hetzner_server }}"
  when: item.labels.app == "worker" or item.labels.app == "master" or  item.labels.app == "bootstrap"
