---
- name: configure HTPasswd identity provider
  hosts: label_app_bastion
  vars:
    - ansible_ssh_private_key_file: auth/ssh-key
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - ansible_user: root
    - ansible_python_interpreter: /usr/bin/python3
  vars_files: 
    - ../auth/hcloud.yml
    - ../inventory/inventory.yml
  roles:
    - ../roles/configure-idp
